type ReportTable = {
  columns: string[];
  rows: Array<Array<string | number>>;
};

type ReportPdfOptions = {
  title: string;
  subtitle: string;
  meta: Array<{ label: string; value: string | number }>;
  summary: Array<{ label: string; value: string | number }>;
  table: ReportTable;
  filename: string;
  footer?: string;
};

const GREEN = '#1E3D2B';
const GOLD = '#D4A017';
const TEXT = '#17211A';
const MUTED = '#667085';
const BORDER = '#D9E5DC';
const SOFT = '#F4F8F5';

function safeText(value: string | number): string {
  return String(value).replace(/[^\x20-\x7E]/g, '-');
}

export async function downloadReportPdf(options: ReportPdfOptions): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let y = 16;

  const addPageIfNeeded = (height: number) => {
    if (y + height <= pageHeight - 18) return;
    pdf.addPage();
    y = 16;
  };

  pdf.setFillColor(GREEN);
  pdf.roundedRect(margin, y, contentWidth, 34, 3, 3, 'F');
  pdf.setTextColor('#FFFFFF');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.text(safeText(options.title), margin + 6, y + 12);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text(safeText(options.subtitle), margin + 6, y + 21);
  pdf.setTextColor(GOLD);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8);
  pdf.text('NATURE LITE ADMIN PANEL', margin + 6, y + 29);
  y += 42;

  const metaWidth = contentWidth / Math.max(options.meta.length, 1);
  options.meta.forEach((item, index) => {
    const x = margin + index * metaWidth;
    pdf.setFillColor(SOFT);
    pdf.roundedRect(x, y, metaWidth - 2, 18, 2, 2, 'F');
    pdf.setTextColor(MUTED);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    pdf.text(safeText(item.label).toUpperCase(), x + 4, y + 6);
    pdf.setTextColor(TEXT);
    pdf.setFontSize(10);
    pdf.text(safeText(item.value), x + 4, y + 13);
  });
  y += 26;

  pdf.setTextColor(TEXT);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.text('Summary', margin, y);
  y += 5;

  const summaryWidth = contentWidth / Math.max(options.summary.length, 1);
  options.summary.forEach((item, index) => {
    const x = margin + index * summaryWidth;
    pdf.setDrawColor(BORDER);
    pdf.setFillColor('#FFFFFF');
    pdf.roundedRect(x, y, summaryWidth - 2, 20, 2, 2, 'FD');
    pdf.setTextColor(MUTED);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7);
    pdf.text(safeText(item.label).toUpperCase(), x + 4, y + 7);
    pdf.setTextColor(GREEN);
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(13);
    pdf.text(safeText(item.value), x + 4, y + 15);
  });
  y += 30;

  pdf.setTextColor(TEXT);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(12);
  pdf.text('Details', margin, y);
  y += 6;

  const columns = options.table.columns;
  const columnWidth = contentWidth / Math.max(columns.length, 1);
  const drawHeader = () => {
    pdf.setFillColor(GREEN);
    pdf.roundedRect(margin, y, contentWidth, 9, 1.5, 1.5, 'F');
    pdf.setTextColor('#FFFFFF');
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(7);
    columns.forEach((column, index) => {
      pdf.text(safeText(column), margin + index * columnWidth + 3, y + 6);
    });
    y += 10;
  };

  drawHeader();

  options.table.rows.forEach((row, rowIndex) => {
    addPageIfNeeded(8);
    if (y === 16) drawHeader();
    pdf.setFillColor(rowIndex % 2 === 0 ? '#FFFFFF' : SOFT);
    pdf.rect(margin, y, contentWidth, 8, 'F');
    pdf.setTextColor(TEXT);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7);
    row.forEach((cell, index) => {
      const value = safeText(cell);
      const text = value.length > 26 ? `${value.slice(0, 23)}...` : value;
      pdf.text(text, margin + index * columnWidth + 3, y + 5.2);
    });
    y += 8;
  });

  addPageIfNeeded(14);
  pdf.setDrawColor(BORDER);
  pdf.line(margin, pageHeight - 13, pageWidth - margin, pageHeight - 13);
  pdf.setTextColor(MUTED);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.text(safeText(options.footer || 'Generated by Nature Lite Admin Panel'), margin, pageHeight - 8);
  pdf.text(new Date().toLocaleString('en-IN'), pageWidth - margin, pageHeight - 8, { align: 'right' });

  pdf.save(options.filename);
}
